apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: cwu8eh2jy-java-quarkus
  janus-idp.io/tekton: cwu8eh2jy-java-quarkus
  backstage.io/kubernetes-id: cwu8eh2jy-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cwu8eh2jy-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
